# -*- coding: utf-8 -*-
"""NLP_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XYUTTjUtk5Z9J3s_SInj4Sn1UoBoJjU0

# Question 5
"""

!pip install fasttext

import fasttext

# Set the training parameters
model = fasttext.train_supervised(input="training_data.txt", lr=1.0, epoch=25, wordNgrams=2, bucket=200000, dim=50, loss='softmax')

# Save the trained model
model.save_model("language_detection_model.bin")

import fasttext

model = fasttext.load_model("language_detection_model.bin")

text = "This is a test sentence"
predictions = model.predict(text)
lang_label = predictions[0][0].replace('__label__', '')
confidence = predictions[1][0]
print(f"Detected language: {lang_label}, Confidence: {confidence}")

