# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PvDKvwV-kVOINWar3nz5_SO1x-sFz1og

# Question 2
"""

import PyPDF2
import pandas as pd
from collections import Counter

def extract_text_from_pdf(file_path):
    with open(file_path, 'rb') as file:
        reader = PyPDF2.PdfFileReader(file)
        num_pages = reader.numPages

        text = ""
        for page in range(num_pages):
            page_obj = reader.getPage(page)
            text += page_obj.extractText()

    return text

def save_text_to_csv(text, csv_file):
    df = pd.DataFrame({'text': [text]})
    df.to_csv(csv_file, index=False)

def find_most_repeated_word(text):
    words = text.split()
    word_counts = Counter(words)
    most_common_word = word_counts.most_common(1)[0][0]

    return most_common_word

if __name__ == "__main__":
    pdf_file = r"F:\DOCUMENTS\iNeuron_Assignment_NAM\FINAL_ASSIGNMENT\Natural_Language_Processing\Data Science.pdf"
    csv_file = "output.csv"

    extracted_text = extract_text_from_pdf(pdf_file)
    save_text_to_csv(extracted_text, csv_file)

    most_common_word = find_most_repeated_word(extracted_text)
    print("Most repeated word:", most_common_word)